Add button variants and FontAwesome Pro (#65)
* Fix usage of extended Header and Text components: using defaultProps and properly passing opacity prop

* Remove element highlighting for app

* Add custom Button component

* Add FontAwesome Pro packages and React dependencies, import specific icons

* Add close button variant, apply button, new FontAwesome times icon, and Header style to Quiz Nav

* Update README

* Set Font Awesome Pro token by environment variable

Because the token is secret, and the repo is public, we can't chuck in the token to the .npmrc file. Luckily said file can read env vars, and the env var can be set manually in Netlify

Refs #64

* Update README

Refs #64

* Reference env file in docker-compose

Add env file checks in STRTA

diff --git a/scripts/server b/scripts/server
--- a/scripts/server
+++ b/scripts/server
@@ -19,6 +19,11 @@ then
     then
         usage
     else
+        if [ ! -f docker-compose.env ]
+        then
+            echo "Missing docker env file. Consult project README."
+            exit 1
+        fi
         docker-compose -f docker-compose.yml up
     fi
 fi
