Reference env file in docker-compose
Add env file checks in STRTA

diff --git a/scripts/update b/scripts/update
--- a/scripts/update
+++ b/scripts/update
@@ -19,6 +19,11 @@ then
     then
         usage
     else
+        if [ ! -f docker-compose.env ]
+        then
+            echo "Missing docker env file. Consult project README."
+            exit 1
+        fi
         # Create dirs expected by docker, if they don't exist
         mkdir -p /vagrant/dist
         mkdir -p /vagrant/src/nginx/srv/dist
